version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: ["npm", "run", "test"]



# Lesson 94 - Going forward you will need to pass a flag to specify which compose file you want to build and run from:
# docker-compose -f docker-compose-dev.yml up
# docker-compose -f docker-compose-dev.yml up --build
# docker-compose -f docker-compose-dev.yml down